### ISSUE TITLE
use strict + const with Node 0.12 throw an error

### ISSUE THREAD

**Issue by Unitech** [keymetrics/fullstack-workshop#1]
```
$ node server.js 
/home/shant/keymetrics/fullstack-workshop/server.js:13
const RANDOM_MIN = 1
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by soyuka** [comment]
Pourtant le script est en strict -_-
